---
- name: Update sources
  become: yes
  apt: update_cache=yes cache_valid_time=86400

- name: Install Deluged
  become: yes
  package: name={{item}} state=present
  with_items:
    - python-mako
    - deluged
    - deluge-web

- name: Ensures ~/.config/deluge dir exists
  file: path=~/.config/deluge state=directory

- name: Check for config path "files/deluge/"
  tags: 
    - deluge-conf
  local_action: stat path="files/deluge/"
  register: result    

- name: Copy deluge-web Conf
  tags: 
    - deluge-conf
  copy: 
    src: files/deluge/
    dest: ~/.config/deluge/
  when: result.stat.exists

- name: Killing deluge-web 
  tags: 
    - deluge-conf  
  shell: pkill -9 deluge-web
  register: bass_result
  failed_when: "bass_result.rc < 0"

- name: Starting deluge-web
  tags: 
    - deluge-conf
  shell: deluge-web &
  async: 2592000

- cron:
    name: "Setting deluge-web cron job when reboot"
    special_time: reboot
    job: "deluge-web &" 