---
- name: Update sources
  become: yes
  apt: update_cache=yes cache_valid_time=86400


- name: Add Java repo (for debian/jessie64)
  become: yes
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main' state=present


- name: Add Java repo (for debian/jessie64) (deb-src)
  become: yes
  apt_repository: repo='deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main' state=present

- name: Add Java repo
  become: yes
  apt_repository: repo='ppa:webupd8team/java' state=present
  retries: 5

- name: Add Java key (for raspbian lite)
  become: yes
  apt_key: 
    keyserver: hkp://keyserver.ubuntu.com:80
    id: EEA14886

- name: Update sources
  become: yes
  apt: update_cache=yes cache_valid_time=86400

- name: accept oracle license
  become: yes
  debconf:
    name: "oracle-java8-installer"
    question: "shared/accepted-oracle-license-v1-1"
    value: "true"
    vtype: "select"

- name: Install Java 8
  become: yes
  apt: name=oracle-java8-installer force=yes
  